'use client';

import { useLocale } from 'next-intl';

export default function PrivacyPage() {
  const locale = useLocale();

  const englishContent = (
    <div className="max-w-4xl mx-auto px-6 py-12 text-muted-foreground leading-relaxed space-y-6">
      <h1 className="text-primary font-black uppercase tracking-wide text-3xl">Privacy Policy</h1>
      <p>Last updated: June 24, 2026</p>
      <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
      <p>We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a href="https://www.termsfeed.com/privacy-policy-generator/" target="_blank" className="text-primary underline">Privacy Policy Generator</a>.</p>

      <h2 className="text-primary font-black uppercase tracking-wide text-2xl">Interpretation and Definitions</h2>
      <h3 className="text-primary font-bold text-xl">Interpretation</h3>
      <p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
      <h3 className="text-primary font-bold text-xl">Definitions</h3>
      <p>For the purposes of this Privacy Policy:</p>
      <ul className="list-disc pl-5 space-y-2">
        <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
        <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
        <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to Couch Expert.</li>
        <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
        <li><strong>Country</strong> refers to: Nevada,  United States</li>
        <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
        <li><strong>Personal Data</strong> (or "Personal Information") is any information that relates to an identified or identifiable individual. We use "Personal Data" and "Personal Information" interchangeably unless a law uses a specific term.</li>
        <li><strong>Service</strong> refers to the Website.</li>
        <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
        <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
        <li><strong>Website</strong> refers to Couch Expert, accessible from <a href="https://vercel.app" rel="external nofollow noopener" target="_blank" className="text-primary underline">https://vercel.app</a>.</li>
        <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
      </ul>

      <h2 className="text-primary font-black uppercase tracking-wide text-2xl">Collecting and Using Your Personal Data</h2>
      <h3 className="text-primary font-bold text-xl">Types of Data Collected</h3>
      <h4 className="text-primary font-semibold text-lg">Personal Data</h4>
      <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
      <ul className="list-disc pl-5 space-y-2">
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Address, State, Province, ZIP/Postal code, City</li>
      </ul>
      <div className="bg-blue-50 p-4 rounded-lg border-l-4 border-blue-500">
        <h5 className="font-bold text-blue-800">Google Authentication</h5>
        <p>When you choose to sign in via Google Authentication, we collect your email address and display name (as provided by Google) solely for the purpose of creating and managing your account. This data is used to authenticate you and personalize your experience within our Service. We do not receive or store your Google password.</p>
      </div>
      <div className="bg-blue-50 p-4 rounded-lg border-l-4 border-blue-500">
        <h5 className="font-bold text-blue-800">Social Media Links</h5>
        <p>Users may optionally link their social media profiles (e.g., Twitter, Instagram, Facebook) to their account. If you choose to provide social media links, we store those links as part of your profile data. We do not access your social media accounts or collect any data from them beyond the publicly visible links you provide.</p>
      </div>
      <h4 className="text-primary font-semibold text-lg">Usage Data</h4>
      <p>Usage Data is collected automatically when using the Service.</p>
      <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
      <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
      <p>We may also collect information that Your browser sends whenever You visit Our Service or when You access the Service by or through a mobile device.</p>
      <h4 className="text-primary font-semibold text-lg">Tracking Technologies and Cookies</h4>
      <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
      <ul className="list-disc pl-5 space-y-2">
        <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
        <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
      </ul>
      <div className="bg-blue-50 p-4 rounded-lg border-l-4 border-blue-500">
        <h5 className="font-bold text-blue-800">Yandex.Metrika and Webvisor</h5>
        <p>We use Yandex.Metrika, a web analytics service provided by Yandex, to analyze user behavior and improve our interface. Yandex.Metrika uses cookies to collect information such as your IP address, browser type, pages visited, and time spent on pages. The Webvisor feature may record anonymized user sessions (clicks, mouse movements, scrolling) for interface optimization. This data is aggregated and cannot be used to identify you personally. You can opt out of Yandex.Metrika tracking via your browser settings or Yandex's opt‑out page.</p>
      </div>
      <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>
      <p>Where required by law, we use non-essential cookies (such as analytics, advertising, and remarketing cookies) only with Your consent. You can withdraw or change Your consent at any time using Our cookie preferences tool (if available) or through Your browser/device settings. Withdrawing consent does not affect the lawfulness of processing based on consent before its withdrawal.</p>
      <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
      <ul className="list-disc pl-5 space-y-2">
        <li>
          <strong>Necessary / Essential Cookies</strong>
          <p>Type: Session Cookies</p>
          <p>Administered by: Us</p>
          <p>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
        </li>
        <li>
          <strong>Cookies Policy / Notice Acceptance Cookies</strong>
          <p>Type: Persistent Cookies</p>
          <p>Administered by: Us</p>
          <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
        </li>
        <li>
          <strong>Functionality Cookies</strong>
          <p>Type: Persistent Cookies</p>
          <p>Administered by: Us</p>
          <p>Purpose: These Cookies allow Us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
        </li>
      </ul>
      <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of Our Privacy Policy.</p>

      <h3 className="text-primary font-bold text-xl">Use of Your Personal Data</h3>
      <p>The Company may use Personal Data for the following purposes:</p>
      <ul className="list-disc pl-5 space-y-2">
        <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
        <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
        <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
        <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
        <li><strong>To provide You</strong> with news, special offers, and general information about other goods, services and events which We offer that are similar to those that you have already purchased or inquired about unless You have opted not to receive such information.</li>
        <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
        <li><strong>For business transfers:</strong> We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</li>
        <li><strong>For other purposes</strong>: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
      </ul>
      <p>We may share Your Personal Data in the following situations:</p>
      <ul className="list-disc pl-5 space-y-2">
        <li><strong>With Service Providers:</strong> We may share Your Personal Data with Service Providers to monitor and analyze the use of our Service,  to contact You.</li>
        <li><strong>For business transfers:</strong> We may share or transfer Your Personal Data in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
        <li><strong>With Affiliates:</strong> We may share Your Personal Data with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
        <li><strong>With business partners:</strong> We may share Your Personal Data with Our business partners to offer You certain products, services or promotions.</li>
        <li><strong>With other users:</strong> If Our Service offers public areas, when You share Personal Data or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
        <li><strong>With Your consent</strong>: We may disclose Your Personal Data for any other purpose with Your consent.</li>
      </ul>

      <h3 className="text-primary font-bold text-xl">Retention of Your Personal Data</h3>
      <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if We are required to retain Your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
      <p>Where possible, We apply shorter retention periods and/or reduce identifiability by deleting, aggregating, or anonymizing data. Unless otherwise stated, the retention periods below are maximum periods ("up to") and We may delete or anonymize data sooner when it is no longer needed for the relevant purpose. We apply different retention periods to different categories of Personal Data based on the purpose of processing and legal obligations:</p>
      <ul className="list-disc pl-5 space-y-2">
        <li>
          <strong>Account Information</strong>
          <ul className="list-disc pl-5 space-y-1">
            <li>User Accounts: retained for the duration of your account relationship plus up to 24 months after account closure to handle any post-termination issues or resolve disputes.</li>
          </ul>
        </li>
        <li>
          <strong>Customer Support Data</strong>
          <ul className="list-disc pl-5 space-y-1">
            <li>Support tickets and correspondence: up to 24 months from the date of ticket closure to resolve follow-up inquiries, track service quality, and defend against potential legal claims</li>
            <li>Chat transcripts: up to 24 months for quality assurance and staff training purposes.</li>
          </ul>
        </li>
        <li>
          <strong>Usage Data</strong>
          <ul className="list-disc pl-5 space-y-1">
            <li>Website analytics data (cookies, IP addresses, device identifiers): up to 24 months from the date of collection, which allows us to analyze trends while respecting privacy principles.</li>
            <li>Server logs (IP addresses, access times): up to 24 months for security monitoring and troubleshooting purposes.</li>
          </ul>
        </li>
      </ul>
      <p>Usage Data is retained in accordance with the retention periods described above, and may be retained longer only where necessary for security, fraud prevention, or legal compliance.</p>
      <p>We may retain Personal Data beyond the periods stated above for different reasons:</p>
      <ul className="list-disc pl-5 space-y-2">
        <li>Legal obligation: We are required by law to retain specific data (e.g., financial records for tax authorities).</li>
        <li>Legal claims: Data is necessary to establish, exercise, or defend legal claims.</li>
        <li>Your explicit request: You ask Us to retain specific information.</li>
        <li>Technical limitations: Data exists in backup systems that are scheduled for routine deletion.</li>
      </ul>
      <p>You may request information about how long We will retain Your Personal Data by contacting Us.</p>
      <p>When retention periods expire, We securely delete or anonymize Personal Data according to the following procedures:</p>
      <ul className="list-disc pl-5 space-y-2">
        <li>Deletion: Personal Data is removed from Our systems and no longer actively processed.</li>
        <li>Backup retention: Residual copies may remain in encrypted backups for a limited period consistent with our backup retention schedule and are not restored except where necessary for security, disaster recovery, or legal compliance.</li>
        <li>Anonymization: In some cases, We convert Personal Data into anonymous statistical data that cannot be linked back to You. This anonymized data may be retained indefinitely for research and analytics.</li>
      </ul>

      <h3 className="text-primary font-bold text-xl">Transfer of Your Personal Data</h3>
      <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.</p>
      <p>Where required by applicable law, We will ensure that international transfers of Your Personal Data are subject to appropriate safeguards and supplementary measures where appropriate. The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>

      <h3 className="text-primary font-bold text-xl">Delete Your Personal Data</h3>
      <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
      <p>Our Service may give You the ability to delete certain information about You from within the Service.</p>
      <p>You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any Personal Data that You have provided to Us.</p>
      <p>Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>

      <h3 className="text-primary font-bold text-xl">Disclosure of Your Personal Data</h3>
      <h4 className="text-primary font-semibold text-lg">Business Transactions</h4>
      <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
      <h4 className="text-primary font-semibold text-lg">Law enforcement</h4>
      <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
      <h4 className="text-primary font-semibold text-lg">Other legal requirements</h4>
      <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
      <ul className="list-disc pl-5 space-y-2">
        <li>Comply with a legal obligation</li>
        <li>Protect and defend the rights or property of the Company</li>
        <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
        <li>Protect the personal safety of Users of the Service or the public</li>
        <li>Protect against legal liability</li>
      </ul>

      <h3 className="text-primary font-bold text-xl">Security of Your Personal Data</h3>
      <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

      <h2 className="text-primary font-black uppercase tracking-wide text-2xl">Children's Privacy</h2>
      <p>Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 16 without verification of parental consent, We take steps to remove that information from Our servers.</p>
      <p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>

      <h2 className="text-primary font-black uppercase tracking-wide text-2xl">Links to Other Websites</h2>
      <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
      <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

      <h2 className="text-primary font-black uppercase tracking-wide text-2xl">Changes to this Privacy Policy</h2>
      <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
      <p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>
      <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

      <h2 className="text-primary font-black uppercase tracking-wide text-2xl">Contact Us</h2>
      <p>If you have any questions about this Privacy Policy, You can contact us:</p>
      <ul className="list-disc pl-5 space-y-2">
        <li>By email: <a href="mailto:support@couchexpert.com" className="text-primary underline">support@couchexpert.com</a></li>
      </ul>
    </div>
  );

  const russianContent = (
    <div className="max-w-4xl mx-auto px-6 py-12 text-muted-foreground leading-relaxed space-y-6">
      <h1 className="text-primary font-black uppercase tracking-wide text-3xl">Политика конфиденциальности</h1>
      <p>Последнее обновление: 24 июня 2026 г.</p>
      <p>Настоящая Политика конфиденциальности описывает наши принципы и процедуры сбора, использования и раскрытия Вашей информации при использовании Сервиса и информирует Вас о Ваших правах на конфиденциальность и о том, как закон защищает Вас.</p>
      <p>Мы используем Ваши Персональные данные для предоставления и улучшения Сервиса. Используя Сервис, Вы соглашаетесь на сбор и использование информации в соответствии с настоящей Политикой конфиденциальности. Настоящая Политика конфиденциальности была создана при помощи <a href="https://www.termsfeed.com/privacy-policy-generator/" target="_blank" className="text-primary underline">Генератора политики конфиденциальности</a>.</p>

      <h2 className="text-primary font-black uppercase tracking-wide text-2xl">Толкование и определения</h2>
      <h3 className="text-primary font-bold text-xl">Толкование</h3>
      <p>Слова, начальные буквы которых написаны с заглавной буквы, имеют значения, определенные при следующих условиях. Следующие определения имеют одинаковое значение независимо от того, появляются ли они в единственном или во множественном числе.</p>
      <h3 className="text-primary font-bold text-xl">Определения</h3>
      <p>Для целей настоящей Политики конфиденциальности:</p>
      <ul className="list-disc pl-5 space-y-2">
        <li><strong>Аккаунт</strong> означает уникальную учетную запись, созданную для Вас для доступа к нашему Сервису или его частям.</li>
        <li><strong>Аффилированное лицо</strong> означает организацию, которая контролирует, находится под контролем или находится под общим контролем с стороной, где "контроль" означает владение 50% или более акций, долевого участия или других ценных бумаг, дающих право голоса при избрании директоров или иного управляющего органа.</li>
        <li><strong>Компания</strong> (в настоящей Политике конфиденциальности именуемая как "Компания", "Мы", "Нас" или "Наш") относится к Couch Expert.</li>
        <li><strong>Куки (Cookies)</strong> — это небольшие файлы, которые размещаются на Вашем компьютере, мобильном устройстве или любом другом устройстве веб-сайтом и содержат подробности истории Вашего просмотра на этом веб-сайте среди множества их применений.</li>
        <li><strong>Страна</strong> относится к: Невада, США.</li>
        <li><strong>Устройство</strong> означает любое устройство, которое может получить доступ к Сервису, такое как компьютер, сотовый телефон или цифровой планшет.</li>
        <li><strong>Персональные данные</strong> (или "Персональная информация") — это любая информация, которая относится к идентифицированному или идентифицируемому физическому лицу. Мы используем термины "Персональные данные" и "Персональная информация" взаимозаменяемо, если закон не использует конкретный термин.</li>
        <li><strong>Сервис</strong> относится к Веб-сайту.</li>
        <li><strong>Поставщик услуг</strong> означает любое физическое или юридическое лицо, которое обрабатывает данные от имени Компании. Это относится к сторонним компаниям или физическим лицам, нанятым Компанией для облегчения Сервиса, предоставления Сервиса от имени Компании, выполнения услуг, связанных с Сервисом, или помощи Компании в анализе использования Сервиса.</li>
        <li><strong>Данные об использовании</strong> относятся к данным, собираемым автоматически, либо генерируемым при использовании Сервиса, либо из инфраструктуры самого Сервиса (например, продолжительность посещения страницы).</li>
        <li><strong>Веб-сайт</strong> относится к Couch Expert, доступному по адресу <a href="https://vercel.app" rel="external nofollow noopener" target="_blank" className="text-primary underline">https://vercel.app</a>.</li>
        <li><strong>Вы</strong> означает физическое лицо, получающее доступ или использующее Сервис, или компанию, или другое юридическое лицо, от имени которого такое физическое лицо получает доступ или использует Сервис, в зависимости от обстоятельств.</li>
      </ul>

      <h2 className="text-primary font-black uppercase tracking-wide text-2xl">Сбор и использование Ваших персональных данных</h2>
      <h3 className="text-primary font-bold text-xl">Типы собираемых данных</h3>
      <h4 className="text-primary font-semibold text-lg">Персональные данные</h4>
      <p>При использовании нашего Сервиса мы можем попросить Вас предоставить нам определенную личную информацию, которая может быть использована для связи или идентификации Вас. Личная информация может включать, но не ограничивается:</p>
      <ul className="list-disc pl-5 space-y-2">
        <li>Адрес электронной почты</li>
        <li>Имя и фамилия</li>
        <li>Адрес, штат, провинция, почтовый индекс, город</li>
      </ul>
      <div className="bg-blue-50 p-4 rounded-lg border-l-4 border-blue-500">
        <h5 className="font-bold text-blue-800">Google Аутентификация</h5>
        <p>Когда вы выбираете вход через Google Аутентификацию, мы собираем ваш адрес электронной почты и отображаемое имя (предоставленные Google) исключительно для создания и управления вашей учетной записью. Эти данные используются для аутентификации и персонализации вашего опыта в нашем Сервисе. Мы не получаем и не храним ваш пароль от Google.</p>
      </div>
      <div className="bg-blue-50 p-4 rounded-lg border-l-4 border-blue-500">
        <h5 className="font-bold text-blue-800">Ссылки на социальные сети</h5>
        <p>Пользователи могут по желанию привязать свои профили в социальных сетях (например, Twitter, Instagram, Facebook) к своей учетной записи. Если вы решите предоставить ссылки на социальные сети, мы храним эти ссылки как часть данных вашего профиля. Мы не получаем доступ к вашим аккаунтам в социальных сетях и не собираем никакие данные из них, кроме публично видимых ссылок, которые вы предоставляете.</p>
      </div>
      <h4 className="text-primary font-semibold text-lg">Данные об использовании</h4>
      <p>Данные об использовании собираются автоматически при использовании Сервиса.</p>
      <p>Данные об использовании могут включать такую информацию, как IP-адрес Вашего Устройства, тип браузера, версия браузера, страницы нашего Сервиса, которые Вы посещаете, время и дата Вашего посещения, время, проведенное на этих страницах, уникальные идентификаторы устройств и другие диагностические данные.</p>
      <p>Когда Вы получаете доступ к Сервису через мобильное устройство, мы можем автоматически собирать определенную информацию, включая, но не ограничиваясь, тип мобильного устройства, которое Вы используете, уникальный ID Вашего мобильного устройства, IP-адрес Вашего мобильного устройства, операционную систему мобильного устройства, тип мобильного интернет-браузера, который Вы используете, уникальные идентификаторы устройств и другие диагностические данные.</p>
      <p>Мы также можем собирать информацию, которую Ваш браузер отправляет всякий раз, когда Вы посещаете наш Сервис или когда Вы получаете доступ к Сервису через мобильное устройство.</p>
      <h4 className="text-primary font-semibold text-lg">Технологии отслеживания и куки</h4>
      <p>Мы используем Куки и аналогичные технологии отслеживания для отслеживания активности на нашем Сервисе и хранения определенной информации. Технологии отслеживания, которые мы используем, включают маяки, теги и скрипты для сбора и отслеживания информации, а также для улучшения и анализа нашего Сервиса. Технологии, которые мы используем, могут включать:</p>
      <ul className="list-disc pl-5 space-y-2">
        <li><strong>Куки или браузерные куки.</strong> Куки — это небольшой файл, размещаемый на Вашем Устройстве. Вы можете дать указание своему браузеру отказаться от всех Куки или указывать, когда Куки отправляется. Однако, если Вы не принимаете Куки, Вы, возможно, не сможете использовать некоторые части нашего Сервиса.</li>
        <li><strong>Веб-маяки.</strong> Определенные разделы нашего Сервиса и наши электронные письма могут содержать небольшие электронные файлы, известные как веб-маяки (также называемые прозрачными гифками, пиксельными тегами и однопиксельными гифками), которые позволяют Компании, например, подсчитывать пользователей, посетивших эти страницы или открывших электронное письмо, и для другой связанной статистики веб-сайта (например, записи популярности определенного раздела и проверки целостности системы и сервера).</li>
      </ul>
      <div className="bg-blue-50 p-4 rounded-lg border-l-4 border-blue-500">
        <h5 className="font-bold text-blue-800">Яндекс.Метрика и Вебвизор</h5>
        <p>Мы используем Яндекс.Метрику, сервис веб-аналитики от Яндекса, для анализа поведения пользователей и улучшения нашего интерфейса. Яндекс.Метрика использует куки для сбора информации, такой как ваш IP-адрес, тип браузера, посещенные страницы и время, проведенное на страницах. Функция Вебвизор может записывать анонимизированные сессии пользователей (клики, движения мыши, прокрутка) для оптимизации интерфейса. Эти данные агрегируются и не могут быть использованы для личной идентификации. Вы можете отказаться от отслеживания Яндекс.Метрикой через настройки браузера или страницу отказа Яндекса.</p>
      </div>
      <p>Куки могут быть "Постоянными" или "Сессионными". Постоянные Куки остаются на Вашем персональном компьютере или мобильном устройстве, когда Вы находитесь в офлайн-режиме, тогда как Сессионные Куки удаляются, как только Вы закрываете веб-браузер.</p>
      <p>Там, где это требуется по закону, мы используем необязательные куки (такие как аналитические, рекламные и ремаркетинговые куки) только с Вашего согласия. Вы можете отозвать или изменить свое согласие в любое время, используя наш инструмент настройки куки (если доступен) или через настройки Вашего браузера/устройства. Отзыв согласия не влияет на законность обработки, основанной на согласии до его отзыва.</p>
      <p>Мы используем как Сессионные, так и Постоянные Куки для целей, указанных ниже:</p>
      <ul className="list-disc pl-5 space-y-2">
        <li>
          <strong>Необходимые / Основные куки</strong>
          <p>Тип: Сессионные куки</p>
          <p>Администрируется: Нами</p>
          <p>Цель: Эти куки необходимы для предоставления Вам услуг, доступных через Веб-сайт, и для того, чтобы Вы могли использовать некоторые его функции. Они помогают аутентифицировать пользователей и предотвращать мошенническое использование учетных записей. Без этих куки услуги, которые Вы запросили, не могут быть предоставлены, и мы используем эти куки только для предоставления Вам этих услуг.</p>
        </li>
        <li>
          <strong>Куки принятия политики куки / уведомления</strong>
          <p>Тип: Постоянные куки</p>
          <p>Администрируется: Нами</p>
          <p>Цель: Эти куки определяют, приняли ли пользователи использование куки на Веб-сайте.</p>
        </li>
        <li>
          <strong>Функциональные куки</strong>
          <p>Тип: Постоянные куки</p>
          <p>Администрируется: Нами</p>
          <p>Цель: Эти куки позволяют Нам запоминать выбор, который Вы делаете при использовании Веб-сайта, например, запоминать данные для входа или языковые предпочтения. Цель этих куки — предоставить Вам более персонализированный опыт и избежать необходимости каждый раз заново вводить Ваши предпочтения при использовании Веб-сайта.</p>
        </li>
      </ul>
      <p>Для получения дополнительной информации о куки, которые мы используем, и Вашем выборе в отношении куки, пожалуйста, посетите нашу Политику использования куки или раздел Куки нашей Политики конфиденциальности.</p>

      <h3 className="text-primary font-bold text-xl">Использование Ваших персональных данных</h3>
      <p>Компания может использовать Персональные данные для следующих целей:</p>
      <ul className="list-disc pl-5 space-y-2">
        <li><strong>Для предоставления и поддержания нашего Сервиса</strong>, включая мониторинг использования нашего Сервиса.</li>
        <li><strong>Для управления Вашей учетной записью:</strong> для управления Вашей регистрацией как пользователя Сервиса. Персональные данные, которые Вы предоставляете, могут дать Вам доступ к различным функциям Сервиса, доступным Вам как зарегистрированному пользователю.</li>
        <li><strong>Для исполнения договора:</strong> разработка, соблюдение и выполнение договора купли-продажи продуктов, предметов или услуг, которые Вы приобрели, или любого другого договора с Нами через Сервис.</li>
        <li><strong>Для связи с Вами:</strong> Для связи с Вами по электронной почте, телефонным звонкам, SMS или другим эквивалентным формам электронной связи, таким как push-уведомления мобильного приложения относительно обновлений или информационных сообщений, связанных с функциями, продуктами или заключенными услугами, включая обновления безопасности, когда это необходимо или разумно для их реализации.</li>
        <li><strong>Для предоставления Вам</strong> новостей, специальных предложений и общей информации о других товарах, услугах и мероприятиях, которые мы предлагаем и которые аналогичны тем, которые Вы уже приобрели или о которых спрашивали, если Вы не отказались от получения такой информации.</li>
        <li><strong>Для управления Вашими запросами:</strong> Для рассмотрения и управления Вашими запросами к Нам.</li>
        <li><strong>Для бизнес-переводов:</strong> Мы можем использовать Ваши Персональные данные для оценки или проведения слияния, выделения, реструктуризации, реорганизации, роспуска или другой продажи или передачи некоторых или всех наших активов, будь то в качестве действующего предприятия или в рамках процедуры банкротства, ликвидации или аналогичной процедуры, при которой Персональные данные, хранящиеся у Нас о пользователях нашего Сервиса, входят в состав передаваемых активов.</li>
        <li><strong>Для других целей</strong>: Мы можем использовать Вашу информацию для других целей, таких как анализ данных, выявление тенденций использования, определение эффективности наших рекламных кампаний и для оценки и улучшения нашего Сервиса, продуктов, услуг, маркетинга и Вашего опыта.</li>
      </ul>
      <p>Мы можем делиться Вашими Персональными данными в следующих ситуациях:</p>
      <ul className="list-disc pl-5 space-y-2">
        <li><strong>С Поставщиками услуг:</strong> Мы можем делиться Вашими Персональными данными с Поставщиками услуг для мониторинга и анализа использования нашего Сервиса, для связи с Вами.</li>
        <li><strong>Для бизнес-переводов:</strong> Мы можем делиться или передавать Ваши Персональные данные в связи с переговорами о любом слиянии, продаже активов Компании, финансировании или приобретении всей или части нашего бизнеса другой компанией.</li>
        <li><strong>С Аффилированными лицами:</strong> Мы можем делиться Вашими Персональными данными с Нашими аффилированными лицами, и в этом случае мы потребуем от этих аффилированных лиц соблюдать настоящую Политику конфиденциальности. Аффилированные лица включают нашу материнскую компанию и любые другие дочерние компании, партнеров по совместному предприятию или другие компании, которые Мы контролируем или которые находятся под общим контролем с Нами.</li>
        <li><strong>С деловыми партнерами:</strong> Мы можем делиться Вашими Персональными данными с Нашими деловыми партнерами, чтобы предложить Вам определенные продукты, услуги или акции.</li>
        <li><strong>С другими пользователями:</strong> Если наш Сервис предлагает общедоступные области, когда Вы делитесь Персональными данными или иным образом взаимодействуете в общедоступных областях с другими пользователями, такая информация может быть просмотрена всеми пользователями и может быть публично распространена за пределами.</li>
        <li><strong>С Вашего согласия</strong>: Мы можем раскрывать Ваши Персональные данные для любой другой цели с Вашего согласия.</li>
      </ul>

      <h3 className="text-primary font-bold text-xl">Хранение Ваших персональных данных</h3>
      <p>Компания будет хранить Ваши Персональные данные только в течение срока, необходимого для целей, изложенных в настоящей Политике конфиденциальности. Мы будем хранить и использовать Ваши Персональные данные в той мере, в какой это необходимо для выполнения наших юридических обязательств (например, если мы обязаны хранить Ваши данные в соответствии с применимым законодательством), разрешения споров и обеспечения соблюдения наших юридических соглашений и политик.</p>
      <p>По возможности мы применяем более короткие сроки хранения и/или снижаем идентифицируемость путем удаления, агрегирования или анонимизации данных. Если не указано иное, приведенные ниже сроки хранения являются максимальными ("до"), и мы можем удалить или анонимизировать данные раньше, когда они больше не нужны для соответствующей цели. Мы применяем разные сроки хранения к разным категориям Персональных данных в зависимости от цели обработки и юридических обязательств:</p>
      <ul className="list-disc pl-5 space-y-2">
        <li>
          <strong>Информация об учетной записи</strong>
          <ul className="list-disc pl-5 space-y-1">
            <li>Учетные записи пользователей: хранятся в течение срока действия отношений с учетной записью плюс до 24 месяцев после закрытия учетной записи для решения любых пост-терминационных вопросов или разрешения споров.</li>
          </ul>
        </li>
        <li>
          <strong>Данные поддержки клиентов</strong>
          <ul className="list-disc pl-5 space-y-1">
            <li>Тикеты поддержки и переписка: до 24 месяцев с даты закрытия тикета для решения последующих запросов, отслеживания качества обслуживания и защиты от потенциальных юридических претензий.</li>
            <li>Транскрипты чатов: до 24 месяцев для обеспечения качества и обучения персонала.</li>
          </ul>
        </li>
        <li>
          <strong>Данные об использовании</strong>
          <ul className="list-disc pl-5 space-y-1">
            <li>Данные веб-аналитики (куки, IP-адреса, идентификаторы устройств): до 24 месяцев с даты сбора, что позволяет нам анализировать тенденции, соблюдая принципы конфиденциальности.</li>
            <li>Логи сервера (IP-адреса, время доступа): до 24 месяцев для мониторинга безопасности и устранения неполадок.</li>
          </ul>
        </li>
      </ul>
      <p>Данные об использовании хранятся в соответствии с описанными выше сроками хранения и могут храниться дольше только при необходимости для безопасности, предотвращения мошенничества или соблюдения законодательства.</p>
      <p>Мы можем хранить Персональные данные сверх указанных выше периодов по разным причинам:</p>
      <ul className="list-disc pl-5 space-y-2">
        <li>Юридическое обязательство: Мы обязаны по закону хранить определенные данные (например, финансовые записи для налоговых органов).</li>
        <li>Юридические претензии: Данные необходимы для установления, осуществления или защиты юридических претензий.</li>
        <li>Ваш явный запрос: Вы просите Нас сохранить определенную информацию.</li>
        <li>Технические ограничения: Данные существуют в системах резервного копирования, которые запланированы для регулярного удаления.</li>
      </ul>
      <p>Вы можете запросить информацию о том, как долго Мы будем хранить Ваши Персональные данные, связавшись с Нами.</p>
      <p>Когда сроки хранения истекают, Мы безопасно удаляем или анонимизируем Персональные данные в соответствии со следующими процедурами:</p>
      <ul className="list-disc pl-5 space-y-2">
        <li>Удаление: Персональные данные удаляются из наших систем и больше не обрабатываются активно.</li>
        <li>Резервное копирование: Остаточные копии могут оставаться в зашифрованных резервных копиях в течение ограниченного периода в соответствии с нашим графиком хранения резервных копий и не восстанавливаются, за исключением случаев, когда это необходимо для безопасности, восстановления после сбоев или соблюдения законодательства.</li>
        <li>Анонимизация: В некоторых случаях Мы преобразуем Персональные данные в анонимные статистические данные, которые не могут быть связаны с Вами. Эти анонимизированные данные могут храниться неограниченное время для исследований и аналитики.</li>
      </ul>

      <h3 className="text-primary font-bold text-xl">Передача Ваших персональных данных</h3>
      <p>Ваша информация, включая Персональные данные, обрабатывается в операционных офисах Компании и в любых других местах, где находятся стороны, участвующие в обработке. Это означает, что эта информация может быть передана и храниться на компьютерах, расположенных за пределами Вашего штата, провинции, страны или другой государственной юрисдикции, где законы о защите данных могут отличаться от законов Вашей юрисдикции.</p>
      <p>Там, где это требуется применимым законодательством, Мы обеспечим, чтобы международные передачи Ваших Персональных данных подлежали соответствующим гарантиям и дополнительным мерам, где это уместно. Компания предпримет все разумно необходимые шаги, чтобы обеспечить безопасную обработку Ваших данных в соответствии с настоящей Политикой конфиденциальности, и передача Ваших Персональных данных в организацию или страну не будет происходить, если там не будут обеспечены адекватные меры контроля, включая безопасность Ваших данных и другой личной информации.</p>

      <h3 className="text-primary font-bold text-xl">Удаление Ваших персональных данных</h3>
      <p>Вы имеете право удалить или запросить, чтобы Мы помогли удалить Персональные данные, которые Мы собрали о Вас.</p>
      <p>Наш Сервис может предоставить Вам возможность удалить определенную информацию о Вас изнутри Сервиса.</p>
      <p>Вы можете обновлять, изменять или удалять свою информацию в любое время, войдя в свою Учетную запись, если она у Вас есть, и посетив раздел настроек учетной записи, который позволяет управлять Вашей личной информацией. Вы также можете связаться с Нами, чтобы запросить доступ, исправление или удаление любых Персональных данных, которые Вы предоставили Нам.</p>
      <p>Обратите внимание, однако, что нам может потребоваться сохранить определенную информацию, когда у нас есть юридическое обязательство или законное основание для этого.</p>

      <h3 className="text-primary font-bold text-xl">Раскрытие Ваших персональных данных</h3>
      <h4 className="text-primary font-semibold text-lg">Бизнес-транзакции</h4>
      <p>Если Компания участвует в слиянии, поглощении или продаже активов, Ваши Персональные данные могут быть переданы. Мы уведомим Вас до передачи Ваших Персональных данных, и они станут предметом другой Политики конфиденциальности.</p>
      <h4 className="text-primary font-semibold text-lg">Правоохранительные органы</h4>
      <p>При определенных обстоятельствах Компания может быть обязана раскрыть Ваши Персональные данные, если это требуется по закону или в ответ на действительные запросы государственных органов (например, суда или государственного агентства).</p>
      <h4 className="text-primary font-semibold text-lg">Другие юридические требования</h4>
      <p>Компания может раскрывать Ваши Персональные данные в добросовестной уверенности, что такие действия необходимы для:</p>
      <ul className="list-disc pl-5 space-y-2">
        <li>Соблюдения юридического обязательства</li>
        <li>Защиты и защиты прав или собственности Компании</li>
        <li>Предотвращения или расследования возможных правонарушений в связи с Сервисом</li>
        <li>Защиты личной безопасности Пользователей Сервиса или общественности</li>
        <li>Защиты от юридической ответственности</li>
      </ul>

      <h3 className="text-primary font-bold text-xl">Безопасность Ваших персональных данных</h3>
      <p>Безопасность Ваших Персональных данных важна для Нас, но помните, что ни один метод передачи через Интернет или метод электронного хранения не является на 100% безопасным. Хотя Мы стремимся использовать коммерчески приемлемые средства для защиты Ваших Персональных данных, Мы не можем гарантировать их абсолютную безопасность.</p>

      <h2 className="text-primary font-black uppercase tracking-wide text-2xl">Конфиденциальность детей</h2>
      <p>Наш Сервис не предназначен для лиц младше 16 лет. Мы сознательно не собираем личную информацию от лиц младше 16 лет. Если Вы являетесь родителем или опекуном и Вы знаете, что Ваш ребенок предоставил Нам Персональные данные, пожалуйста, свяжитесь с Нами. Если Мы узнаем, что Мы собрали Персональные данные от лица младше 16 лет без проверки согласия родителей, Мы предпримем шаги для удаления этой информации с наших серверов.</p>
      <p>Если Нам необходимо полагаться на согласие как на правовое основание для обработки Вашей информации, и Ваша страна требует согласия от родителя, Мы можем потребовать согласия Вашего родителя перед сбором и использованием этой информации.</p>

      <h2 className="text-primary font-black uppercase tracking-wide text-2xl">Ссылки на другие веб-сайты</h2>
      <p>Наш Сервис может содержать ссылки на другие веб-сайты, которые не управляются Нами. Если Вы нажмете на стороннюю ссылку, Вы будете перенаправлены на сайт этой третьей стороны. Мы настоятельно рекомендуем Вам ознакомиться с Политикой конфиденциальности каждого сайта, который Вы посещаете.</p>
      <p>Мы не контролируем и не несем ответственности за содержание, политики конфиденциальности или практики любых сторонних сайтов или услуг.</p>

      <h2 className="text-primary font-black uppercase tracking-wide text-2xl">Изменения в настоящей Политике конфиденциальности</h2>
      <p>Мы можем время от времени обновлять нашу Политику конфиденциальности. Мы уведомим Вас о любых изменениях, разместив новую Политику конфиденциальности на этой странице.</p>
      <p>Мы сообщим Вам по электронной почте и/или через заметное уведомление в нашем Сервисе до того, как изменение вступит в силу, и обновим дату "Последнего обновления" в верхней части настоящей Политики конфиденциальности.</p>
      <p>Вам рекомендуется периодически просматривать настоящую Политику конфиденциальности на предмет любых изменений. Изменения в настоящей Политике конфиденциальности вступают в силу с момента их размещения на этой странице.</p>

      <h2 className="text-primary font-black uppercase tracking-wide text-2xl">Свяжитесь с нами</h2>
      <p>Если у Вас есть какие-либо вопросы по поводу настоящей Политики конфиденциальности, Вы можете связаться с нами:</p>
      <ul className="list-disc pl-5 space-y-2">
        <li>По электронной почте: <a href="mailto:support@couchexpert.com" className="text-primary underline">support@couchexpert.com</a></li>
      </ul>
    </div>
  );

  return locale === 'en' ? englishContent : russianContent;
}