export { getRegisterSchema } from "./register.schema"
export type { TypeRegisterSchema } from "./register.schema"
export { getLoginSchema } from "./login.schema"
export type { TypeLoginSchema } from "./login.schema"
export { getResetPasswordSchema } from "./reset-password.schema"
export type { TypeResetPasswordSchema } from "./reset-password.schema"
export { getNewPasswordSchema } from "./new-password.schema"
export type { TypeNewPasswordSchema } from "./new-password.schema"
export { getPasswordValidation, passwordValidation } from "./password.schema"